export const countries = [
  "China",
  "Brazil",
  "Spain",
  "Iran",
  "Indonesia",
  "India",
  "United States",
  "Turkey",
  "Mexico",
  "Malaysia",
  "Italy",
  "Poland",
  "South Korea",
  "France",
  "Egypt",
  "Portugal",
  "Argentina",
  "Thailand",
  "Saudi Arabia",
  "Chile",
  "Japan",
  "Tunisia",
  "United Kingdom",
  "Russian Federation",
  "Canada",
  "Colombia",
  "Australia",
  "Viet Nam",
  "Greece",
  "Pakistan",
  "Ecuador",
  "Ireland",
  "Oman",
  "Romania",
  "Germany",
  "Iraq",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Palestine",
  "Serbia",
  "South Africa",
  "Taiwan",
  "New Zealand",
  "Sweden",
  "Belgium",
  "Cuba",
  "Lithuania",
  "Peru",
  "Algeria",
  "Bulgaria",
  "Israel",
  "Kazakhstan",
  "Morocco",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Singapore",
  "Syrian Arab Republic",
  "Yemen",
  "Brunei Darussalam",
  "Cote d'Ivoire",
  "Finland",
  "Guyana",
  "Honduras",
  "Hungary",
  "Jordan",
  "Kuwait",
  "Luxembourg",
  "Myanmar",
  "Philippines",
  "Puerto Rico",
  "Qatar",
  "Slovakia",
  "Switzerland",
  "Ukraine",
  "United Arab Emirates",
];
